# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created: Thu Mar 18 17:59:25 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(470, 394)
        Preferences.setSizeGripEnabled(False)
        self.tabWidget = QtGui.QTabWidget(Preferences)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 451, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.serversTab = QtGui.QWidget()
        self.serversTab.setObjectName("serversTab")
        self.groupBox_2 = QtGui.QGroupBox(self.serversTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 431, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cctrayPathList = QtGui.QListView(self.groupBox_2)
        self.cctrayPathList.setGeometry(QtCore.QRect(0, 21, 419, 211))
        self.cctrayPathList.setObjectName("cctrayPathList")
        self.addButton = QtGui.QPushButton(self.groupBox_2)
        self.addButton.setGeometry(QtCore.QRect(380, 240, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setObjectName("addButton")
        self.removeButton = QtGui.QPushButton(self.groupBox_2)
        self.removeButton.setGeometry(QtCore.QRect(330, 240, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setObjectName("removeButton")
        self.tabWidget.addTab(self.serversTab, "")
        self.miscTab = QtGui.QWidget()
        self.miscTab.setObjectName("miscTab")
        self.groupBox = QtGui.QGroupBox(self.miscTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 421, 131))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 401, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.successfulBuildsCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.successfulBuildsCheckbox.setObjectName("successfulBuildsCheckbox")
        self.gridLayout_2.addWidget(self.successfulBuildsCheckbox, 0, 0, 1, 1)
        self.brokenBuildsCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.brokenBuildsCheckbox.setObjectName("brokenBuildsCheckbox")
        self.gridLayout_2.addWidget(self.brokenBuildsCheckbox, 0, 1, 1, 1)
        self.fixedBuildsCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.fixedBuildsCheckbox.setObjectName("fixedBuildsCheckbox")
        self.gridLayout_2.addWidget(self.fixedBuildsCheckbox, 1, 0, 1, 1)
        self.stillFailingBuildsCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.stillFailingBuildsCheckbox.setObjectName("stillFailingBuildsCheckbox")
        self.gridLayout_2.addWidget(self.stillFailingBuildsCheckbox, 1, 1, 1, 1)
        self.connectivityIssuesCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.connectivityIssuesCheckbox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.connectivityIssuesCheckbox.setObjectName("connectivityIssuesCheckbox")
        self.gridLayout_2.addWidget(self.connectivityIssuesCheckbox, 2, 0, 1, 1)
        self.showLastBuildTimeCheckbox = QtGui.QCheckBox(self.miscTab)
        self.showLastBuildTimeCheckbox.setGeometry(QtCore.QRect(10, 200, 351, 31))
        self.showLastBuildTimeCheckbox.setObjectName("showLastBuildTimeCheckbox")
        self.layoutWidget1 = QtGui.QWidget(self.miscTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 150, 421, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timezoneLabel = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timezoneLabel.sizePolicy().hasHeightForWidth())
        self.timezoneLabel.setSizePolicy(sizePolicy)
        self.timezoneLabel.setMinimumSize(QtCore.QSize(210, 0))
        self.timezoneLabel.setObjectName("timezoneLabel")
        self.horizontalLayout.addWidget(self.timezoneLabel)
        self.timezoneList = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timezoneList.sizePolicy().hasHeightForWidth())
        self.timezoneList.setSizePolicy(sizePolicy)
        self.timezoneList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.timezoneList.setObjectName("timezoneList")
        self.horizontalLayout.addWidget(self.timezoneList)
        self.tabWidget.addTab(self.miscTab, "")
        self.buttonBox = QtGui.QDialogButtonBox(Preferences)
        self.buttonBox.setGeometry(QtCore.QRect(40, 350, 421, 32))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.timezoneLabel.setBuddy(self.timezoneList)

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(QtGui.QApplication.translate("Preferences", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Preferences", "Monitored servers", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setToolTip(QtGui.QApplication.translate("Preferences", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("Preferences", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setToolTip(QtGui.QApplication.translate("Preferences", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("Preferences", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.serversTab), QtGui.QApplication.translate("Preferences", "Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Preferences", "Notification settings", None, QtGui.QApplication.UnicodeUTF8))
        self.successfulBuildsCheckbox.setText(QtGui.QApplication.translate("Preferences", "successful builds", None, QtGui.QApplication.UnicodeUTF8))
        self.brokenBuildsCheckbox.setText(QtGui.QApplication.translate("Preferences", "broken builds", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedBuildsCheckbox.setText(QtGui.QApplication.translate("Preferences", "fixed builds", None, QtGui.QApplication.UnicodeUTF8))
        self.stillFailingBuildsCheckbox.setText(QtGui.QApplication.translate("Preferences", "still failing builds", None, QtGui.QApplication.UnicodeUTF8))
        self.connectivityIssuesCheckbox.setText(QtGui.QApplication.translate("Preferences", "connectivity issues", None, QtGui.QApplication.UnicodeUTF8))
        self.showLastBuildTimeCheckbox.setText(QtGui.QApplication.translate("Preferences", "show last build time for each project", None, QtGui.QApplication.UnicodeUTF8))
        self.timezoneLabel.setText(QtGui.QApplication.translate("Preferences", "Server timezone", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.miscTab), QtGui.QApplication.translate("Preferences", "Misc", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
