#!/usr/bin/env python

from distutils.core import setup

setup (name='BuildNotify',
       version='0.01',
       description='Cruise Control build monitor',
       author='Anay Nayak',
       author_email='anayak007@gmail.com',
       license='GPL',
       packages=['buildnotifylib'],
       scripts = ['buildnotifyapplet.py'],
       data_files=[
        ('share/buildnotify/pixmaps',['icons/icon-failure.png', 
            'icons/icon-failure-building.png',
            'icons/icon-success.png',
            'icons/icon-inactive.png',
            'icons/icon-success-building.png']),
        ('share/buildnotify',['data/add_server.glade', 'data/preferences.glade']),
        ('lib/bonobo/servers',['data/GNOME_BuildNotifyApplet.server'])])

