version: 2
jobs:
  build:
    working_directory: ~/buildnotify
    docker:
      - image: ubuntu:19.04
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get -qq update
            apt-get install -y -qq python3-pip xvfb curl git
            pip3 install tox
            pip3 install paver
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/cc-test-reporter
            chmod +x ~/cc-test-reporter
      - run:
          name: run tests
          command: |
            ~/cc-test-reporter before-build
            tox -ecoverage
            ~/cc-test-reporter after-build --exit-code $?
            paver dist_pypi
            pip install dist/*.tar.gz
  deploy:
    docker:
      - image: ubuntu:19.04
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get -qq update
            apt-get install -y -qq python3-pip curl
            pip3 install paver twine
      - run: echo "export BUILD_VERSION=`python3 buildnotifylib/version.py`" >> $BASH_ENV
      - run:
          name: upload to pypi
          command: |
            paver release_pypi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
